### ISSUE TITLE
Analysis container class

### ISSUE THREAD

**Issue by rubendegroote** [woutergins/satlas#12]
We should further the development of what is currently the Analysis class. 

What we would need:
1. A class that gathers spectrum objects, for different analysis approaches of a given datafile or set of data files. So, one (Combined)spectrum (with isomers) for each approach for one or a few data files. This is what the Analysis class currently implements, though that name may not be well chosen.
1. A class that gathers several of the above objects, used for analysis of a big set of data files. 

Suggestions for names for these are welcome. 

These two classes will have methods to analyse and plot with code one-liners, do aggregate analysis (e.g. Average of parameters of a whole dataset), big plot and save operations, batch methods,...

**Comment by woutergins** [comment]
Just created a branch from development for this called 'Analysis'.

**Comment by rubendegroote** [comment]
Branch went pretty dead, but I think this discussion can be moved to #35? That one does not have anything related to saving the model objects, but it does have many similar points.

**Comment by woutergins** [comment]
Indeed, #35 supersedes this issue. Closing.
