### ISSUE TITLE
Importing for satlas

### ISSUE THREAD

**Issue by rubendegroote** [woutergins/satlas#14]
We should make it easier for users to import from satlas.

Rught now, we need to do: from satlas.spectrum import Spectrum.

There are two issues with this: 
1: We may change our file system, which breaks existing code.
2: Users need to know the structure of the code to be able to import. For now, this is fine, but long-term, we may want to evolve to (even) more of a black box.

We can solve these issues quite easily by writing appropriate **init**.py files and defining **all** in .py files. (https://docs.python.org/2/tutorial/modules.html) 

See also this talk: https://www.youtube.com/watch?v=0oTh1CXRaQ0
Many good tips there!

**Comment by woutergins** [comment]
I had a quick try using the **all** variable in the packages. I pushed this to the latest version of development, might want to have a look at it.

**Comment by woutergins** [comment]
Importing now works; refining this should be possible, but the code is much more accessible now.
