### ISSUE TITLE
Plot smooth fit

### ISSUE THREAD

**Issue by woutergins** [woutergins/satlas#3]
Create a convenience function that plots the spectrum in a smooth way, given an axis and optional x-values.

**Comment by rubendegroote** [comment]
Even though you self-assigned, I did it in my branch.

**Comment by rubendegroote** [comment]
So far there is a plotting function for SingleSpectrum and for CombinedSpectrum.

**Comment by woutergins** [comment]
Plotting has been written for IsomerSpectrum, and small bugfix has been issued for CombinedSpectrum.

**Comment by rubendegroote** [comment]
Issue can be closed I guess?

**Comment by woutergins** [comment]
True, it's no longer an issue. I was leaving this open because I would like to make to code a bit more consistent/flexible.
