### ISSUE TITLE
Installation as a python package

### ISSUE THREAD

**Issue by rubendegroote** [woutergins/satlas#5]
This would allow for easier import from several locations, and is probably also required to enable unpickling of e.g. Spectrum objects.

**Comment by rubendegroote** [comment]
https://packaging.python.org/en/latest/distributing.html

**Comment by woutergins** [comment]
The description is a bit messed up, but the latest master version is now available on pypi. The way to update this is uploading the tarball from github (made from the latest tag) to PyPi as a source file.
